const teaDetailsData = [
  {
    link: 'hibicious-flower',
    name: 'Hibicious Flower',
    price: '7.00',
    product_img: '/images/teas/teabag1.png',
    product_description: 'loremasdasdwa',
    product_info: 'loremasdwadsd',
  },
  {
    link: 'chamomile-tea',
    name: 'Chamomile Tea',
    price: '8.00',
    product_img: '/images/teas/teabag2.png',
    product_description: 'loremasdasdwa',
    product_info: 'loremasdwadsd',
  },
  {
    link: 'raspberry-leaves',
    name: 'Raspberry Leaves',
    price: '8.00',
    product_img: '/images/teas/teabag3.png',
    product_description: 'loremasdasdwa',
    product_info: 'loremasdwadsd',
  },
  {
    link: 'rosemary-specials',
    name: 'Rosemary Specials',
    price: '5.00',
    product_img: '/images/teas/teabag4.png',
    product_description: 'loremasdasdwa',
    product_info: 'loremasdwadsd',
  },
  {
    link: 'earl-grey',
    name: 'Earl Grey',
    price: '6.00',
    product_img: '/images/teas/teabag5.png',
    product_description: 'loremasdasdwa',
    product_info: 'loremasdwadsd',
  },
  {
    link: 'lavender-blend',
    name: 'Lavender Blend',
    price: '7.00',
    product_img: '/images/teas/teabag6.png',
    product_description: 'loremasdasdwa',
    product_info: 'loremasdwadsd',
  },
  {
    link: 'almond-spice',
    name: 'Almond Spice',
    price: '15.00',
    product_img: '/images/teas/teabag7.png',
    product_description: 'loremasdasdwa',
    product_info: 'loremasdwadsd',
  },
  {
    link: 'rose-flowers',
    name: 'Rose Flowers',
    price: '13.00',
    product_img: '/images/teas/teabag8.png',
    product_description: 'loremasdasdwa',
    product_info: 'loremasdwadsd',
  },
  {
    link: 'mint-&-melissa-mix',
    name: 'Mint & Melissa Mix',
    price: '15.00',
    product_img: '/images/teas/teabag9.png',
    product_description: 'loremasdasdwa',
    product_info: 'loremasdwadsd',
  },
];
export default teaDetailsData;
